# fly.toml file generated for shaun-standalone-3 on 2021-11-22T17:59:45-06:00

app = "shaun-standalone-3"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[checks]

  [checks.pg]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/flycheck/pg"
    port = 5500
    timeout = "10s"
    type = "http"

  [checks.role]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/flycheck/role"
    port = 5500
    timeout = "10s"
    type = "http"

  [checks.vm]
    grace_period = "1s"
    interval = "1m"
    method = "get"
    path = "/flycheck/vm"
    port = 5500
    timeout = "10s"
    type = "http"

[env]


[experimental]
  allowed_public_ports = []
  auto_rollback = false
  private_network = true

[[mounts]]
  destination = "/data"
  source = "pg_data"
