name: Release

on:
  create:

jobs:
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-20.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: "Fetch latest tag"
        id: get-latest-tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      -
        name: Build and push Postgres 14
        id: docker_build_14
        uses: docker/build-push-action@v3
        with:
          build-args: |
            PG_VERSION=14.6
            VERSION=${{ steps.get-latest-tag.outputs.tag }}
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            flyio/postgres-flex:14
            flyio/postgres-flex:14.6
      -
        name: Postgres 14 Image digest
        run: echo ${{ steps.docker_build_14.outputs.digest }}
